### ISSUE TITLE
Error in mailer

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/instieventsportal#2]
Error Occurred
{ [Error: Invalid login]
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/answer/14257 xg3sm7782992pbb.64 - gsmtp',
  responseCode: 535 }
@deepakpadamata know how to fix this?

**Comment by deepakpadamata** [comment]
Check out erp-2016/server/components/mailer/index.js
It has a working mailer module. You have to install
nodemailer-direct-transport. Server has its own mailing system, so we use
that in erp, do the same.
If we are hosting on insti server then someone will have to put Gmail
credentials on it.
